DELETE FROM clienteentity;
INSERT INTO clienteentity (usuario,ipmodem,longitud,latitud,direccion,cedula,direccioncaja,departamento,localidad,barrio,longitudcaja,latitudcaja,errada,usaApp,tipoPredio)  VALUES ('cbetonia0@unblog.fr','155.248.50.138',NULL,NULL,'CJC 1-2','1015123456','Carrera 4# 23-01','BOGOTA','BOGOTA','BOSQUE CALDERON TEJADA 1 ',NULL,NULL,FALSE,FALSE,NULL);
INSERT INTO clienteentity (usuario,ipmodem,longitud,latitud,direccion,cedula,direccioncaja,departamento,localidad,barrio,longitudcaja,latitudcaja,errada,usaApp,tipoPredio)  VALUES ('eboothby1@ovh.net','80.248.21.143',NULL,NULL,'CJC 1-3','3247678654','Calle 91# 49-67','BOGOTA','BOGOTA','CHAPINERO ALTO 1 ',NULL,NULL,FALSE,TRUE,NULL);
INSERT INTO clienteentity (usuario,ipmodem,longitud,latitud,direccion,cedula,direccioncaja,departamento,localidad,barrio,longitudcaja,latitudcaja,errada,usaApp,tipoPredio)  VALUES ('athon2@mediafire.com','250194178158',NULL,NULL,'Calle 55# 78-57','8661662603','Calle 55# 78-57','BOGOTA','BOGOTA','EL CASTILLO 1 ',NULL,NULL,FALSE,TRUE,NULL);
INSERT INTO clienteentity (usuario,ipmodem,longitud,latitud,direccion,cedula,direccioncaja,departamento,localidad,barrio,longitudcaja,latitudcaja,errada,usaApp,tipoPredio)  VALUES ('stidey3@facebook.com','236.43.120.5',NULL,NULL,'CJC 1-5','1019742935','Calle 22# 4-03','BOGOTA','BOGOTA','EL PARAISO 1 ',NULL,NULL,FALSE,FALSE,NULL);
INSERT INTO clienteentity (usuario,ipmodem,longitud,latitud,direccion,cedula,direccioncaja,departamento,localidad,barrio,longitudcaja,latitudcaja,errada,usaApp,tipoPredio)  VALUES ('lchimenti4@reverbnation.com','92.202.40.87',NULL,NULL,'CJC 1-6','4715079019','Calle 84# 74-42','BOGOTA','BOGOTA','EMAUS 1 ',NULL,NULL,FALSE,TRUE,NULL);
INSERT INTO clienteentity (usuario,ipmodem,longitud,latitud,direccion,cedula,direccioncaja,departamento,localidad,barrio,longitudcaja,latitudcaja,errada,usaApp,tipoPredio)  VALUES ('mgrancher5@mysql.com','89.157.128.78',NULL,NULL,'Calle 86# 48-85','9733459168','Calle 86# 48-85','BOGOTA','BOGOTA','GRANADA 1',NULL,NULL,FALSE,TRUE,NULL);
INSERT INTO clienteentity (usuario,ipmodem,longitud,latitud,direccion,cedula,direccioncaja,departamento,localidad,barrio,longitudcaja,latitudcaja,errada,usaApp,tipoPredio)  VALUES ('ebaskeyfied6@sourceforge.net','216.254.108.92',NULL,NULL,'CJC 1-8','1022730815','Calle 64# 83-94','BOGOTA','BOGOTA','INGEMAR 1',NULL,NULL,FALSE,FALSE,NULL);
INSERT INTO clienteentity (usuario,ipmodem,longitud,latitud,direccion,cedula,direccioncaja,departamento,localidad,barrio,longitudcaja,latitudcaja,errada,usaApp,tipoPredio)  VALUES ('wdehooch7@auda.org.au','71212114210',NULL,NULL,'CJC 1-9','7899745709','Calle 31# 89-25','BOGOTA','BOGOTA','JUAN XXIII 1 ',NULL,NULL,FALSE,TRUE,NULL);
INSERT INTO clienteentity (usuario,ipmodem,longitud,latitud,direccion,cedula,direccioncaja,departamento,localidad,barrio,longitudcaja,latitudcaja,errada,usaApp,tipoPredio)  VALUES ('siddison8@exblog.jp','154.111.243.23',NULL,NULL,'CJC 1-10','2600269920','Calle 55# 53-49','BOGOTA','BOGOTA','LA SALLE 1 ',NULL,NULL,FALSE,TRUE,NULL);
INSERT INTO clienteentity (usuario,ipmodem,longitud,latitud,direccion,cedula,direccioncaja,departamento,localidad,barrio,longitudcaja,latitudcaja,errada,usaApp,tipoPredio)  VALUES ('ppetrowsky9@geocities.com','32124249193',NULL,NULL,'Calle 86# 22-33','528627418','Calle 86# 22-33','BOGOTA','BOGOTA','LAS ACACIAS 1 ',NULL,NULL,FALSE,TRUE,NULL);
INSERT INTO clienteentity (usuario,ipmodem,longitud,latitud,direccion,cedula,direccioncaja,departamento,localidad,barrio,longitudcaja,latitudcaja,errada,usaApp,tipoPredio)  VALUES ('dsigginsa@shareasale.com','120.71.243.62',NULL,NULL,'CJC 1-12','1022521796','Carrera 59# 63-58','BOGOTA','BOGOTA','LOS OLIVOS 1 ',NULL,NULL,FALSE,FALSE,NULL);
INSERT INTO clienteentity (usuario,ipmodem,longitud,latitud,direccion,cedula,direccioncaja,departamento,localidad,barrio,longitudcaja,latitudcaja,errada,usaApp,tipoPredio)  VALUES ('bbohlensb@wiley.com','77.34.38.157',NULL,NULL,'CJC 1-13','7356378281','Calle 99# 45-86','BOGOTA','BOGOTA','MARIA CRISTINA 1 ',NULL,NULL,FALSE,TRUE,NULL);
INSERT INTO clienteentity (usuario,ipmodem,longitud,latitud,direccion,cedula,direccioncaja,departamento,localidad,barrio,longitudcaja,latitudcaja,errada,usaApp,tipoPredio)  VALUES ('dfernezc@weather.com','113.90.51.15',NULL,NULL,'CJC 1-14','3008741923','Calle 4# 12-51','BOGOTA','BOGOTA','MARISCAL SUCRE',NULL,NULL,FALSE,TRUE,NULL);
INSERT INTO clienteentity (usuario,ipmodem,longitud,latitud,direccion,cedula,direccioncaja,departamento,localidad,barrio,longitudcaja,latitudcaja,errada,usaApp,tipoPredio)  VALUES ('bdutnalld@java.com','65.32.98.217',NULL,NULL,'CJC 1-15','7434555554','Calle 1# 24-46','BOGOTA','BOGOTA','GRANADA 2',NULL,NULL,FALSE,TRUE,NULL);
INSERT INTO clienteentity (usuario,ipmodem,longitud,latitud,direccion,cedula,direccioncaja,departamento,localidad,barrio,longitudcaja,latitudcaja,errada,usaApp,tipoPredio)  VALUES ('wmadsene@state.tx.us','39.54.187.250',NULL,NULL,'Calle 38# 16-3','1638557740','Calle 38# 16-3','BOGOTA','BOGOTA','INGEMAR 2',NULL,NULL,FALSE,TRUE,NULL);
INSERT INTO clienteentity (usuario,ipmodem,longitud,latitud,direccion,cedula,direccioncaja,departamento,localidad,barrio,longitudcaja,latitudcaja,errada,usaApp,tipoPredio)  VALUES ('rscrauniagef@cpanel.net','236.49.121.47',NULL,NULL,'CJC 1-17','1018973566','Carrera 70# 5-47','BOGOTA','BOGOTA','JUAN XXIII 2',NULL,NULL,FALSE,FALSE,NULL);
INSERT INTO clienteentity (usuario,ipmodem,longitud,latitud,direccion,cedula,direccioncaja,departamento,localidad,barrio,longitudcaja,latitudcaja,errada,usaApp,tipoPredio)  VALUES ('sgreenfieldg@tripadvisor.com','138125245120',NULL,NULL,'CJC 1-18','2640064549','Calle 84# 22-14','BOGOTA','BOGOTA','LA SALLE 2',NULL,NULL,FALSE,TRUE,NULL);
INSERT INTO clienteentity (usuario,ipmodem,longitud,latitud,direccion,cedula,direccioncaja,departamento,localidad,barrio,longitudcaja,latitudcaja,errada,usaApp,tipoPredio)  VALUES ('mjimpsonh@intel.com','23.149.90.68',NULL,NULL,'CJC 1-19','8268884808','Calle 67# 89-13','BOGOTA','BOGOTA','LAS ACACIAS 2',NULL,NULL,FALSE,TRUE,NULL);
INSERT INTO clienteentity (usuario,ipmodem,longitud,latitud,direccion,cedula,direccioncaja,departamento,localidad,barrio,longitudcaja,latitudcaja,errada,usaApp,tipoPredio)  VALUES ('gbrookshawi@reference.com','17.63.210.249',NULL,NULL,'CJC 1-20','4125041864','Calle 8# 18-64','BOGOTA','BOGOTA','LOS OLIVOS 2',NULL,NULL,FALSE,TRUE,NULL);
INSERT INTO clienteentity (usuario,ipmodem,longitud,latitud,direccion,cedula,direccioncaja,departamento,localidad,barrio,longitudcaja,latitudcaja,errada,usaApp,tipoPredio)  VALUES ('mllewellyj@wired.com','88157140197',NULL,NULL,'CJC 1-21','4885091161','Calle 2# 66-97','BOGOTA','BOGOTA','MARIA CRISTINA 2',NULL,NULL,FALSE,TRUE,NULL);


DELETE  FROM datosclientecompradoentity;
INSERT INTO datosclientecompradoentity (nombre,cedula,direccionpredio,departamento,ciudad) VALUES ('Juan Perez','1015123456','Carrera 3# 23-01,Calle 78# 7-98','CUN','Bogota');
INSERT INTO datosclientecompradoentity (nombre,cedula,direccionpredio,departamento,ciudad) VALUES ('Nicolas Gomez','1018648484','Calle 21# 4-03,Carrera 12# 98-19','CUN','Bogota');
INSERT INTO datosclientecompradoentity (nombre,cedula,direccionpredio,departamento,ciudad) VALUES ('Andres Ramirez','1018396677','Calle 65# 83-94,Carrera 17# 76-23','CUN','Bogota');
INSERT INTO datosclientecompradoentity (nombre,cedula,direccionpredio,departamento,ciudad) VALUES ('Santiago Uribe','1020752735','Carrera 61# 63-58,Calle 5# 2-65','CUN','Bogota');
INSERT INTO datosclientecompradoentity (nombre,cedula,direccionpredio,departamento,ciudad) VALUES ('Luis Reyes','1019778927','Carrera 69# 5-47,Calle 62# 7-79','CUN','Bogota');

COMMIT;



SELECT * FROM CLIENTEENTITY;